// Import the rendercv function and all the refactored components
#import "lib.typ": *

// Apply the rendercv template with custom configuration
#show: rendercv.with(
  name: "{{ cv.name }}",
  footer-text: "Page 1 of 1",
  last-updated-date-text: "{{ cv.last_updated_date_template }}",
  locale-catalog-language: "{{ locale.language_iso_639_1 }}",
  page-size: "{{ design.page.size }}",
  page-top-margin: {{ design.page.top_margin }},
  page-bottom-margin: {{ design.page.bottom_margin }},
  page-left-margin: {{ design.page.left_margin }},
  page-right-margin: {{ design.page.right_margin }},
  page-show-page-numbering: {{ design.page.show_page_numbering|lower }},
  page-show-last-updated-date: {{ design.page.show_last_updated_date|lower }},
  colors-text: {{ design.colors.text.as_rgb() }},
  colors-name: {{ design.colors.name.as_rgb() }},
  colors-connections: {{ design.colors.connections.as_rgb() }},
  colors-section-titles: {{ design.colors.section_titles.as_rgb() }},
  colors-links: {{ design.colors.links.as_rgb() }},
  colors-last-updated-date-and-page-numbering: {{ design.colors.last_updated_date_and_page_numbering.as_rgb() }},
  text-font-family: "{{ design.text.font_family }}",
  text-font-size: {{ design.text.font_size }},
  text-leading: {{ design.text.leading }},
  text-alignment: "{{ design.text.alignment }}",
  text-date-and-location-column-alignment: {{ design.text.date_and_location_column_alignment }},
  links-underline: {{ design.links.underline|lower }},
  links-use-external-link-icon: {{ design.links.use_external_link_icon|lower }},
  header-name-font-family: "{{ design.header.name_font_family }}",
  header-name-font-size: {{ design.header.name_font_size }},
  header-name-bold: {{ design.header.name_bold|lower }},
  header-small-caps-for-name: {{ design.header.small_caps_for_name|lower }},
  header-photo-width: {{ design.header.photo_width }},
  header-connections-font-family: "{{ design.header.connections_font_family }}",
  header-vertical-space-between-name-and-connections: {{ design.header.vertical_space_between_name_and_connections }},
  header-vertical-space-between-connections-and-first-section: {{ design.header.vertical_space_between_connections_and_first_section }},
  header-horizontal-space-between-connections: {{ design.header.horizontal_space_between_connections }},
  header-separator-between-connections: "{{ design.header.separator_between_connections }}",
  header-alignment: {{ design.header.alignment }},
  section-titles-type: "{{ design.section_titles.type }}",
  section-titles-font-family: "{{ design.section_titles.font_family }}",
  section-titles-font-size: {{ design.section_titles.font_size }},
  section-titles-bold: {{ design.section_titles.bold|lower }},
  section-titles-small-caps: {{ design.section_titles.small_caps|lower }},
  section-titles-line-thickness: {{ design.section_titles.line_thickness }},
  section-titles-vertical-space-above: {{ design.section_titles.vertical_space_above }},
  section-titles-vertical-space-below: {{ design.section_titles.vertical_space_below }},
  entries-date-and-location-width: {{ design.entries.date_and_location_width }},
  entries-left-and-right-margin: {{ design.entries.left_and_right_margin }},
  entries-horizontal-space-between-columns: {{ design.entries.horizontal_space_between_columns }},
  entries-vertical-space-between-entries: {{ design.entries.vertical_space_between_entries }},
  entries-allow-page-break-in-sections: {{ design.entries.allow_page_break_in_sections|lower }},
  entries-allow-page-break-in-entries: {{ design.entries.allow_page_break_in_entries|lower }},
  entries-short-second-row: {{ design.entries.short_second_row|lower }},
  highlights-bullet: "{{ design.highlights.bullet }}",
  highlights-nested-bullet: "{{ design.highlights.nested_bullet }}",
  highlights-top-margin: {{ design.highlights.top_margin }},
  highlights-left-margin: {{ design.highlights.left_margin }},
  highlights-vertical-space-between-highlights: {{ design.highlights.vertical_space_between_highlights }},
  highlights-horizontal-space-between-bullet-and-highlights: {{ design.highlights.horizontal_space_between_bullet_and_highlight }},
  highlights-summary-left-margin: {{ design.highlights.summary_left_margin }},
  entry-types-education-entry-degree-column-width: {{ design.entry_types.education_entry.degree_column_width }},
  date: datetime(
    year: {{ settings.current_date.year }},
    month: {{ settings.current_date.month }},
    day: {{ settings.current_date.day }},
  ),
)
