((* for role in entry.roles *))
((* if loop.first *))
((* else *))
#v(-design-text-leading)
((* endif *))
((* if design.entry_types.consolidated_multi_role_experience_entry.role_date_format == "full" *))
<<role.position|escape_typst_characters>> (<<role.date_string>>)
((* else *))
<<role.position|escape_typst_characters>> (<<role.date_string_only_years>>)
((* endif *))
((* endfor *))