name: Publish to Docker Hub

# GitHub events that triggers the workflow:
on:
  release:
    types:
      - published
  workflow_dispatch: # to make the workflow triggerable manually

jobs:
  call_tests_workflow:
    name: Test
    uses: ./.github/workflows/test.yaml

  push_to_registry:
    name: Release docker image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: rendercv/rendercv

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: rendercv/rendercv
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
